### ISSUE TITLE
The previously visited page will be opened after specific steps

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-lockwise/lockwise-ios#883] opened 2019-03-01 14:53 UTC
Build: 1.4.0 (2880)
Device: iPad Air 2
iOS: 11.4

Preconditions:
- Biometrics to lock/unlock enabled
- Time to lock set to 1 minute

Steps to reproduce:
1. Tap on an login 
2. Tap on the web address to load the page in the preferred browser
3. Go back to lockbox from app switcher
4. Wait for Lockbox to autolock
5. Unlock Lockbox

Actual results:
- The preferred browser will open and load the page previously visited.

**Comment by sashei** [comment] 2019-05-10 18:15
This is a duplicate of #889.

**Closed by sashei** 2019-05-10 18:15 UTC
Labels: bug
