### ISSUE TITLE
Long item titles sometimes cause “Back” text to disappear from button

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockwise/lockwise-ios#864] opened 2019-01-22 23:05 UTC
Unrelated to in progress work but found during recent testing:

![img_0025](https://user-images.githubusercontent.com/49511/51571455-6c58dc00-1e5f-11e9-891b-0c131cb911e5.jpeg)

Very long large titles cause the “Back” text on the back button on the item detail view to disappear.

**Comment by sashei** [comment] 2019-05-10 18:12
Duplicate of #448

**Closed by sashei** 2019-05-10 18:13 UTC
Labels: bug
