### ISSUE TITLE
Missing animation from header

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-lockwise/lockwise-ios#1122] opened 2019-11-11 13:34 UTC
## Steps to reproduce
1. Sing in to Lockwise
2. After the login list is populated, scroll on the list
### Expected behavior
- On previous build there was a animation that stretched the header.
### Device & build information
* Device: iPhone X
* Build version: master branch build number 3809
### Notes
Attachments: 
- Previous version: [Previous .mp4.zip](https://github.com/mozilla-lockwise/lockwise-ios/files/3831511/Previous.mp4.zip)
- Actual version: [Actual.MP4.zip](https://github.com/mozilla-lockwise/lockwise-ios/files/3831512/Actual.MP4.zip)

**Comment by changecourse** [comment] 2019-11-11 20:40
Closing as won't-fix. iOS 13 and consultation with @kaylagalway have concluded that this is functioning as intended, despite the previously built, larger header.

**Closed by changecourse** 2019-11-11 20:40 UTC
