### ISSUE TITLE
No longer able to sign in with authorization code

### ISSUE THREAD

**Issue by csuciu** [mozilla-lockwise/lockwise-ios#662] opened 2018-08-29 10:45 UTC
iPhone X (11.4.1)
v1.2 (2018)

1. Open the app.
2. Enter a valid email to sign in.
3. Enter an incorrect password several times until you're requested to enter the authorization code.
4. Enter the authorization code received via email and hit "Continue".
5. Hit "Continue" on the email page.
6. Hit "Continue" on the password page.
7. Repeat 4, 5, 6.

Result: The authorization code is requested again and again until the process gets blocked for 10 minutes.

**Comment by devinreams** [comment] 2018-08-29 14:36
Thanks for this. If I interpret this correctly: this seems to be a bigger issue as the user cannot sign in _at all_ compared to the original finding where "it asks for this a second time": https://github.com/mozilla-lockbox/lockbox-ios/issues/394 and https://github.com/mozilla/fxa-auth-server/issues/1998

I'll just let the FxA team know and see what they think...

**Comment by davismtl** [comment] 2018-08-29 17:48
I was able to reproduce however, I only needed to enter the authorization code twice.

After entering it the second time, the login was successful. Note that I tested this with Sync and not Lockbox so it is possible that Lockbox goes into a more endless loop. I'll test with Lockbox next.

**Comment by davismtl** [comment] 2018-08-29 17:57
Results of test with Lockbox:

> 5. Hit "Continue" on the email page.
> 6. Hit "Continue" on the password page.

If the password was incorrect, entered the code is step 4), the incorrect password remains filled for step 6. So every time you hit Continue, you keep sending a bad password to FxA which is why the user gets blocked over and over and then for 10 minutes.

Proposal: If after unblocking, we assess that the password is incorrect, don't leave it filled for repeated submits.

However, note that as describe in my last comment, when the password is changed to the correct one after the first block, I still need to unblock myself again. This is pretty annoying and should be fixed.

**Comment by sandysage** [comment] 2019-05-10 17:43
Closing this issue here, knowing the work to address this finding is happening on the FxA side.

**Closed by sandysage** 2019-05-10 17:43 UTC
Labels: bug
