### ISSUE TITLE
Visual glitch when going to a entry screen and going back to the entries list

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-lockwise/lockwise-ios#966] opened 2019-05-13 13:03 UTC
Build: 1.5.0 ( 3240)
Device: iPhone 7
iOS: 12.2

Steps to reproduce: 
1. On the entries list, scroll down to hide the top toolbar
2. Tap on an entry
3. Go back to the entries list

Actual results:
- A visual glitch will be displayed when switching between the entry screen and going back to the entries  list.

Video:
[Recording.MP4.zip](https://github.com/mozilla-lockwise/lockwise-ios/files/3172937/Recording.MP4.zip)

**Comment by sashei** [comment] 2019-05-13 18:16
duplicate of #871

**Closed by sashei** 2019-05-13 18:16 UTC
Labels: bug
