### ISSUE TITLE
Unlocking the app takes to the Get Started page instead of Logins list

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockwise/lockwise-ios#1187] opened 2020-02-07 11:38 UTC
## Steps to reproduce
This is not 100% repro but seen when running the tests automatically and also using the app manually
### Expected behavior
After unlocking the app user is taken to logins list view
### Actual behavior
Unlocking the app takes to Get started screen, it is necessary to enter the password again
### Device & build information
* Device: iPhone 8 (Simulator)
* Build version: master ddf2b35

### Notes
Please see video attached. Have in mind this does not happen 100% of the times but I'm seeing it very often. Trying to understand if there are previous steps that make this happen.
https://youtu.be/cRimtpsnUQ8

**Comment by isabelrios** [comment] 2020-02-07 12:40
My feeling is that this is related to another issue that is happening...after disconnecting and reconnecting the account sometimes the logins list is not shown and whenever that `No logins found` screen is shown this issue is more likely to happen.

**Comment by SimonBasca** [comment] 2020-02-07 14:25
I manage to find steps to reproduce this issue. 

## Steps to reproduce
1. Login to FxA
2. Disconnect from FxA
3. Login to FxA
4. Lock the App
5. Unlock the app using biometrics (Unlocking with biometrics will fail and the user will be redirected to the "Get Started screen")
6. Tap "Get Started"
7. Enter the password

### Actual behavior
- Login list will not populate.

After restarting the app a purple screen will be displayed which I believe is a consequence of the original issue which is #1190.

**Comment by SimonBasca** [comment] 2020-02-07 14:28
Duplicate of #1190.

**Closed** 2020-02-07 14:28 UTC
Labels: defect, regression
